#Train
early_stop_enabled: True
early_stop: 15
eval_k: 10  HR@K NDCG@K

# Path
datapath: ../../data/
log_path: ../log


assign_by_interactions: False

device_split: [0.5, 0.8]

dim_s: 16
dim_m: 32
dim_l: 64

device_types: {}

top_k_ratio: 0.1
top_k_method: 'global'
min_k: 1
